language: node_js
after_success: npm run coverage && cat ./coverage/lcov.info | coveralls
before_install:
  - if [ "$PERF" = "1" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;
      sudo apt-get install glibc-2.10-1 -y;
      sudo apt-get install libstdc++6 -y;
    fi
script:
  - if [ "$PERF" = "" ]; then npm test; fi
  - if [ "$PERF" = "1" ]; then npm run test-perf; fi
env:
  - PERF=1
  - PERF=
node_js:
  - "0.10"
  - "0.12"
matrix:
  fast_finish: true
  allow_failures:
    - env: PERF=1
