language: node_js
after_success: npm run coverage && cat ./coverage/lcov.info | coveralls
before_install:
  - if [ "$PERF" = "1" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;
      sudo apt-get install libc6;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20;
      sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 20;
      sudo update-alternatives --config gcc;
      sudo update-alternatives --config g++;
      sudo update-alternatives --config gcov;
    fi
script:
  - if [ "$PERF" = "" ]; then npm test; fi
  - if [ "$PERF" = "1" ]; then npm run test-perf; fi
env:
  - PERF=1
  - PERF=
node_js:
  - "0.10"
  - "0.12"
matrix:
  fast_finish: true
  allow_failures:
    - env: PERF=1
